# Generated by Django 6.0.3 on 2026-04-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='therapists/cv/'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
