# Generated by Django 6.0.3 on 2026-04-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_therapist_cv_file_therapist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to='therapists/photos/'),
        ),
    ]
