# Generated by Django 6.0.3 on 2026-04-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_seed_therapists'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='price_from_cop',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
