# Generated by Django 6.0.3 on 2026-04-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_therapist_price_from_cop'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='session_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
