# Generated by Django 6.0.3 on 2026-04-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_patient_address_patient_birth_date_patient_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_contact_method',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='reason_for_consultation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='referral_source',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
