# Generated by Django 6.0.3 on 2026-04-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_patient_allergies_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='booking_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='includes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='modality',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
