# Generated by Django 6.0.3 on 2026-04-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_service_audience_service_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='patient',
            name='portal_accent_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='portal_welcome_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='portal_welcome_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
