# Generated by Django 6.0.3 on 2026-04-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_patient_password_hash_patient_portal_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='intake_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patient',
            name='intake_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='intake_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='intake_summary',
            field=models.TextField(blank=True),
        ),
    ]
