# Generated by Django 6.0.3 on 2026-04-04 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_course_category_course_cover_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='promo_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.coursemedia'),
        ),
    ]
