# Generated by Django 6.0.3 on 2026-04-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_appointment_client_age_appointment_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='talks/videos/'),
        ),
    ]
