# Generated by Django 6.0.3 on 2026-04-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_talk_description_talk_end_at_talk_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='featured_video_file',
            field=models.FileField(blank=True, null=True, upload_to='talks/featured/'),
        ),
    ]
