# Generated by Django 6.0.3 on 2026-04-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_talk_featured_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='agenda',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='talk',
            name='modality',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='talk',
            name='organizer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='talk',
            name='participants_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talk',
            name='speaker',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='talk',
            name='topic',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
