# Generated by Django 6.0.3 on 2026-04-05 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_talk_agenda_talk_modality_talk_organizer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_registrations', to='api.patient')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.talk')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('talk', 'patient'), name='uniq_talk_patient_registration')],
            },
        ),
    ]
