# Generated by Django 6.0.3 on 2026-04-05 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_talkregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='api.patient'),
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.UniqueConstraint(condition=models.Q(('patient__isnull', False)), fields=('patient',), name='uniq_testimonial_patient'),
        ),
    ]
