# Generated by Django 6.0.3 on 2026-04-05 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_testimonial_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, max_length=64, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_likes', to='api.patient')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.testimonial')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('testimonial', 'client_id'), name='uniq_testimonial_client_like'), models.UniqueConstraint(condition=models.Q(('patient__isnull', False)), fields=('testimonial', 'patient'), name='uniq_testimonial_patient_like')],
            },
        ),
    ]
