# Generated by Django 5.2.6 on 2026-04-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='stories/images/'),
        ),
    ]
