# Generated by Django 5.2.6 on 2026-04-30 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_forumtopic_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_cop', models.PositiveIntegerField(default=280000)),
                ('price_usd', models.PositiveIntegerField(default=70)),
                ('price_eur', models.PositiveIntegerField(default=70)),
                ('sessions_per_month', models.PositiveSmallIntegerField(default=3)),
                ('sessions_breakdown', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('payment_method', models.CharField(choices=[('transfer', 'Transferencia Bancaria'), ('cash', 'Efectivo'), ('other', 'Otro')], default='transfer', max_length=20)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('sessions_used', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.patient')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='api.membershipplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
