# Generated by Django 5.2.6 on 2026-05-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_membership_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='annual_discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='annual_price_cop',
            field=models.PositiveIntegerField(default=2800000, help_text='Annual price COP'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='annual_price_eur',
            field=models.PositiveIntegerField(default=700, help_text='Annual price EUR'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='annual_price_usd',
            field=models.PositiveIntegerField(default=700, help_text='Annual price USD'),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='monthly_discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price_cop',
            field=models.PositiveIntegerField(default=280000, help_text='Monthly price COP'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price_eur',
            field=models.PositiveIntegerField(default=70, help_text='Monthly price EUR'),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price_usd',
            field=models.PositiveIntegerField(default=70, help_text='Monthly price USD'),
        ),
    ]
