# Generated by Django 5.2.6 on 2026-05-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_membershipplan_annual_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='content_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='description_html',
            field=models.TextField(blank=True),
        ),
    ]
