# Generated by Django 5.2.6 on 2026-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_forumreply_content_html_forumtopic_description_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_html',
            field=models.TextField(blank=True),
        ),
    ]
