# Generated by Django 5.2.6 on 2026-05-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_service_description_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopago_public_key', models.CharField(blank=True, help_text='MercadoPago Public Key (starts with APP_USR-...)', max_length=512)),
                ('mercadopago_access_token', models.CharField(blank=True, help_text='MercadoPago Access Token', max_length=512)),
                ('mercadopago_enabled', models.BooleanField(default=False)),
                ('site_name', models.CharField(blank=True, default='ConexiónLuz', max_length=200)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_whatsapp', models.CharField(blank=True, max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
