# Generated by Django 5.2.6 on 2026-05-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='api.therapist'),
        ),
    ]
