# Generated by Django 5.2.6 on 2026-05-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_storycomment_storylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycomment',
            name='client_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
