# Generated by Django 5.2.6 on 2026-05-24 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_storycomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.forumreply'),
        ),
    ]
