# Generated by Django 5.2.6 on 2026-05-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_forumreply_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTopicLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, max_length=64, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_topic_likes', to='api.patient')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.forumtopic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('topic', 'client_id'), name='uniq_forum_topic_client_like'), models.UniqueConstraint(condition=models.Q(('patient__isnull', False)), fields=('topic', 'patient'), name='uniq_forum_topic_patient_like')],
            },
        ),
    ]
