# Generated by Django 5.2.6 on 2026-05-25 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_forumtopiclike'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('sender_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_url', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
