# Generated by Django 5.2.6 on 2026-05-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_client_id',
            field=models.CharField(blank=True, help_text='Google OAuth Client ID', max_length=512),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
