# Generated by Django 5.2.6 on 2026-05-27 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_sitesettings_google_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('energy_level', models.CharField(choices=[('high', 'Excelente'), ('good', 'Bien'), ('tired', 'Agotado'), ('low', 'Difícil')], max_length=20)),
                ('date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to='api.patient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'date'), name='uniq_daily_checkin_patient_date')],
            },
        ),
    ]
