# Generated by Django 5.2.6 on 2026-05-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_dailycheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_picture_file',
            field=models.ImageField(blank=True, null=True, upload_to='patients/profile/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
