# Generated by Django 5.2.6 on 2026-05-31 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_patient_profile_picture_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followed_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_followers', to='api.patient')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_patients', to='api.patient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('follower', 'followed_patient'), name='uniq_follow_patient')],
            },
        ),
        migrations.CreateModel(
            name='FollowTherapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followed_therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_followers', to='api.therapist')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_therapists', to='api.patient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('follower', 'followed_therapist'), name='uniq_follow_therapist')],
            },
        ),
    ]
