# Generated by Django 5.2.6 on 2026-05-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_followpatient_followtherapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_type',
            field=models.CharField(default='miembro', max_length=50),
        ),
    ]
