# Generated by Django 5.2.6 on 2026-06-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_patient_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='can_publish',
            field=models.BooleanField(default=False),
        ),
    ]
