# Generated by Django 5.2.6 on 2026-07-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfCareActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('exercise', 'Ejercicio Guiado'), ('breathing', 'Técnica de Respiración'), ('test', 'Test de Bienestar')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('duration_label', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('gradient', models.CharField(default='from-indigo-500 to-blue-600', max_length=100)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('steps_or_questions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
