# Generated by Django 5.2.6 on 2026-07-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_selfcareactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#10b981', max_length=20)),
                ('gradient', models.CharField(default='from-emerald-500 to-teal-600', max_length=100)),
                ('inhale', models.PositiveIntegerField(default=4)),
                ('hold1', models.PositiveIntegerField(default=0)),
                ('exhale', models.PositiveIntegerField(default=4)),
                ('hold2', models.PositiveIntegerField(default=0)),
                ('cycles', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuidedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('gradient', models.CharField(default='from-indigo-500 to-blue-600', max_length=100)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WellbeingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_label', models.CharField(default='3 min', max_length=50)),
                ('color', models.CharField(default='#ec4899', max_length=20)),
                ('gradient', models.CharField(default='from-pink-500 to-rose-600', max_length=100)),
                ('tag', models.CharField(default='Clínico', max_length=100)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SelfCareActivity',
        ),
    ]
