# Generated by Django 5.2.6 on 2026-07-31 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_breathingtechnique_guidedexercise_wellbeingtest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.course')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='api.patient')),
            ],
            options={
                'unique_together': {('patient', 'course')},
            },
        ),
    ]
