# Generated by Django 5.2.6 on 2026-08-09 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_patient_cover_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWEDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_id', models.IntegerField()),
                ('resource_tipo', models.CharField(max_length=30)),
                ('resource_escuela', models.CharField(max_length=30)),
                ('resource_tema', models.CharField(max_length=60)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(default='portal', max_length=30)),
                ('was_read', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awe_logs', to='api.patient')),
            ],
            options={
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='AWEUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psych_profile', models.CharField(choices=[('Vigilante', 'Vigilante'), ('Guerrero Agotado', 'Guerrero Agotado'), ('Buscador de Sentido', 'Buscador de Sentido'), ('Corazón Abierto', 'Corazón Abierto'), ('Mente Analítica', 'Mente Analítica')], default='Buscador de Sentido', max_length=30)),
                ('current_emotions', models.JSONField(blank=True, default=list)),
                ('current_week', models.PositiveSmallIntegerField(default=1)),
                ('risk_level', models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('severo', 'Severo'), ('critico', 'Crítico')], default='leve', max_length=10)),
                ('preferred_moment', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche'), ('cualquiera', 'Cualquiera')], default='cualquiera', max_length=20)),
                ('delivered_resource_ids', models.JSONField(blank=True, default=list)),
                ('last_resource_date', models.DateField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='awe_profile', to='api.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
