# Generated by Django 5.2.6 on 2026-08-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_awe_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='lumi_balance',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
