# Generated by Django 5.2.6 on 2026-08-10 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_patient_lumi_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lumi_balance',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.CreateModel(
            name='LumiWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.PositiveIntegerField(default=150)),
                ('total_earned', models.PositiveIntegerField(default=150)),
                ('last_login_bonus_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lumi_wallet', to='api.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LumiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_type', models.CharField(choices=[('welcome_bonus', 'Bono de Bienvenida (150 Lumis)'), ('login_bonus', 'Bono por Inicio de Sesión'), ('daily_checkin', 'Check-in Diario de Bienestar'), ('course_reward', 'Recompensa por Completar Lección'), ('service_redemption', 'Canje por Servicio'), ('admin_credit', 'Crédito Administrativo'), ('admin_debit', 'Débito Administrativo')], max_length=40)),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('reference_code', models.CharField(max_length=100, unique=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.lumiwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
