# Generated by Django 5.2.6 on 2026-08-10 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_patient_lumi_balance_lumiwallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LumiUnlockedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(max_length=50)),
                ('item_id', models.CharField(max_length=100)),
                ('item_title', models.CharField(blank=True, max_length=255)),
                ('lumis_spent', models.PositiveIntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_lumi_items', to='api.patient')),
            ],
            options={
                'unique_together': {('patient', 'item_type', 'item_id')},
            },
        ),
    ]
