# Generated by Django 5.2.6 on 2026-08-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_lumiunlockeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
