# Generated by Django 5.2.6 on 2026-08-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_story_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
