# Generated by Django 5.2.6 on 2026-08-17 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_course_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypostcomment',
            name='like_patient_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='communitypostcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.communitypostcomment'),
        ),
    ]
