# Generated by Django 5.2.6 on 2026-08-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_communitypostcomment_like_patient_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
