from django.urls import path

from . import views

urlpatterns = [
    path("health/", views.health),
    path("auth/admin/login/", views.admin_login),
    path("auth/admin/google/", views.admin_google_login),
    path("dashboard/", views.dashboard),
    path("analytics/", views.analytics),
    path("courses/", views.courses),
    path("courses/stats/", views.course_stats),
    path("courses/<int:course_id>/", views.course_detail),
    path("courses/<int:course_id>/publish/", views.course_publish),
    path("courses/<int:course_id>/media/", views.course_media),
    path("courses/media/<int:media_id>/", views.course_media_detail),
    path("courses/<int:course_id>/promo-video/", views.course_promo_video),
    path("therapists/", views.therapists),
    path("therapists/<int:therapist_id>/", views.therapist_detail),
    path("services/", views.services),
    path("services/<int:service_id>/", views.service_detail),
    path("appointments/", views.appointments),
    path("appointments/<int:appointment_id>/", views.appointment_detail),
    path("talks/", views.talks),
    path("talks/<int:talk_id>/", views.talk_detail),
    path("talks/<int:talk_id>/registrations/", views.talk_registrations),
    path("testimonials/", views.testimonials),
    path("testimonials/<int:testimonial_id>/", views.testimonial_detail),
    path("patients/", views.patients),
    path("patients/<int:patient_id>/", views.patient_detail),
    path("auth/login/", views.patient_login),
    path("auth/register/", views.patient_register),
    path("auth/google/", views.patient_google_login),
    path("portal/me/", views.portal_me),
    path("portal/me/picture/", views.portal_upload_profile_picture),
    path("portal/follow/patient/toggle/", views.portal_follow_patient_toggle),
    path("portal/follow/patient/status/", views.portal_follow_patient_status),
    path("portal/follow/patients/following/", views.portal_follow_patient_list_following),
    path("portal/follow/therapist/toggle/", views.portal_follow_therapist_toggle),
    path("portal/follow/therapist/status/", views.portal_follow_therapist_status),
    path("portal/intake/", views.portal_intake),
    path("portal/daily-checkin/", views.portal_daily_checkin),
    path("portal/courses/", views.portal_courses),
    path("portal/courses/<slug:slug>/", views.portal_course_detail),
    path("portal/courses/<slug:slug>/progress/", views.portal_course_progress),
    path("portal/notifications/", views.portal_notifications),
    path("portal/notifications/read/", views.portal_notifications_read),
    path("public/courses/", views.public_courses),
    path("public/courses/<slug:slug>/", views.public_course_detail),
    path("public/talks/", views.public_talks),
    path("public/talks/<int:talk_id>/register/", views.public_talk_register),
    path("public/calendar/", views.public_calendar),
    path("public/testimonials/", views.public_testimonials),
    path("public/testimonials/me/", views.public_testimonial_me),
    path("public/testimonials/<int:testimonial_id>/like/", views.public_testimonial_like),
    path("public/appointments/", views.public_appointments),
    path("public/appointments/occupied/", views.public_appointments_occupied),
    path("public/stories/", views.public_stories),
    path("public/stories/<int:story_id>/", views.public_story_detail),
    path("public/stories/<int:story_id>/like/", views.public_story_like),
    path("public/stories/<int:story_id>/comment/", views.public_story_comment),
    path("public/stories/comments/<int:comment_id>/", views.public_story_comment_detail),
    path("public/forum/", views.public_forum_topics),
    path("public/forum/<int:topic_id>/", views.public_forum_topic_detail),
    path("public/forum/<int:topic_id>/reply/", views.public_forum_topic_reply),
    path("public/forum/<int:topic_id>/like/", views.public_forum_topic_like),
    path("public/forum/replies/<int:reply_id>/", views.public_forum_reply_detail),
    path("stories/", views.stories),
    path("stories/<int:story_id>/", views.story_detail),
    path("forum/", views.forum_topics),
    path("forum/<int:topic_id>/", views.forum_topic_detail),
    path("forum/<int:topic_id>/replies/", views.forum_topic_replies),
    path("forum/replies/<int:reply_id>/", views.forum_reply_detail),
    # Membership
    path("memberships/plans/", views.membership_plans),
    path("memberships/plans/<int:plan_id>/", views.membership_plan_detail),
    path("memberships/subscriptions/", views.membership_subscriptions),
    path("memberships/subscriptions/<int:sub_id>/", views.membership_subscription_detail),
    path("public/memberships/plans/", views.public_membership_plans),
    # Site Settings & MercadoPago
    path("settings/", views.site_settings),
    path("settings/mercadopago/test/", views.mercadopago_test_connection),
    path("payments/mercadopago/preference/", views.mercadopago_create_preference),
    path("payments/mercadopago/pay/", views.mercadopago_pay),
    path("public/settings/", views.public_site_settings),
    # Community posts (feed)
    path("public/community-posts/", views.public_community_posts),
    path("portal/community-posts/", views.portal_community_posts),
    path("portal/community-posts/<int:post_id>/", views.portal_community_post_detail),
    path("portal/community-posts/<int:post_id>/like/", views.portal_community_post_like),
    path("portal/community-posts/<int:post_id>/comment/", views.portal_community_post_comment),
    path("portal/community-posts/comments/<int:comment_id>/", views.portal_community_post_comment_detail),
    # Admin moderation
    path("admin/community-posts/", views.admin_community_posts),
    path("admin/community-posts/<int:post_id>/", views.admin_community_post_detail),
    # Live Chat
    path("portal/chat/send/", views.portal_chat_send),
    path("portal/chat/messages/", views.portal_chat_messages),
    path("admin/chat/sessions/", views.admin_chat_sessions),
    path("admin/chat/sessions/<str:client_id>/", views.admin_chat_session_detail),
    path("admin/chat/send/", views.admin_chat_send),
    path("admin/chat/link/", views.admin_chat_link_patient),
    # Guided Exercises
    path("portal/guided-exercises/", views.portal_guided_exercises),
    path("admin/guided-exercises/", views.admin_guided_exercises),
    path("admin/guided-exercises/<int:exercise_id>/", views.admin_guided_exercise_detail),
    # Breathing Techniques
    path("portal/breathing-techniques/", views.portal_breathing_techniques),
    path("admin/breathing-techniques/", views.admin_breathing_techniques),
    path("admin/breathing-techniques/<int:technique_id>/", views.admin_breathing_technique_detail),
    # Wellbeing Tests
    path("portal/wellbeing-tests/", views.portal_wellbeing_tests),
    path("admin/wellbeing-tests/", views.admin_wellbeing_tests),
    path("admin/wellbeing-tests/<int:test_id>/", views.admin_wellbeing_test_detail),
]
