from django.urls import path

from . import views

urlpatterns = [
    path("health/", views.health),
    path("auth/admin/login/", views.admin_login),
    path("dashboard/", views.dashboard),
    path("analytics/", views.analytics),
    path("courses/", views.courses),
    path("courses/stats/", views.course_stats),
    path("courses/<int:course_id>/", views.course_detail),
    path("courses/<int:course_id>/publish/", views.course_publish),
    path("courses/<int:course_id>/media/", views.course_media),
    path("courses/media/<int:media_id>/", views.course_media_detail),
    path("courses/<int:course_id>/promo-video/", views.course_promo_video),
    path("therapists/", views.therapists),
    path("therapists/<int:therapist_id>/", views.therapist_detail),
    path("services/", views.services),
    path("services/<int:service_id>/", views.service_detail),
    path("appointments/", views.appointments),
    path("appointments/<int:appointment_id>/", views.appointment_detail),
    path("talks/", views.talks),
    path("talks/<int:talk_id>/", views.talk_detail),
    path("talks/<int:talk_id>/registrations/", views.talk_registrations),
    path("testimonials/", views.testimonials),
    path("testimonials/<int:testimonial_id>/", views.testimonial_detail),
    path("patients/", views.patients),
    path("patients/<int:patient_id>/", views.patient_detail),
    path("auth/login/", views.patient_login),
    path("auth/register/", views.patient_register),
    path("portal/me/", views.portal_me),
    path("portal/intake/", views.portal_intake),
    path("portal/courses/", views.portal_courses),
    path("portal/courses/<slug:slug>/", views.portal_course_detail),
    path("portal/courses/<slug:slug>/progress/", views.portal_course_progress),
    path("public/courses/", views.public_courses),
    path("public/courses/<slug:slug>/", views.public_course_detail),
    path("public/talks/", views.public_talks),
    path("public/talks/<int:talk_id>/register/", views.public_talk_register),
    path("public/calendar/", views.public_calendar),
    path("public/testimonials/", views.public_testimonials),
    path("public/testimonials/me/", views.public_testimonial_me),
    path("public/testimonials/<int:testimonial_id>/like/", views.public_testimonial_like),
    path("public/appointments/", views.public_appointments),
    path("public/appointments/occupied/", views.public_appointments_occupied),
    path("public/stories/", views.public_stories),
    path("public/stories/<int:story_id>/", views.public_story_detail),
    path("public/forum/", views.public_forum_topics),
    path("public/forum/<int:topic_id>/", views.public_forum_topic_detail),
    path("public/forum/<int:topic_id>/reply/", views.public_forum_topic_reply),
    path("stories/", views.stories),
    path("stories/<int:story_id>/", views.story_detail),
    path("forum/", views.forum_topics),
    path("forum/<int:topic_id>/", views.forum_topic_detail),
    path("forum/<int:topic_id>/replies/", views.forum_topic_replies),
    path("forum/replies/<int:reply_id>/", views.forum_reply_detail),
    # Membership
    path("memberships/plans/", views.membership_plans),
    path("memberships/plans/<int:plan_id>/", views.membership_plan_detail),
    path("memberships/subscriptions/", views.membership_subscriptions),
    path("memberships/subscriptions/<int:sub_id>/", views.membership_subscription_detail),
    path("public/memberships/plans/", views.public_membership_plans),
    # Site Settings & MercadoPago
    path("settings/", views.site_settings),
    path("settings/mercadopago/test/", views.mercadopago_test_connection),
    path("payments/mercadopago/preference/", views.mercadopago_create_preference),
    path("payments/mercadopago/pay/", views.mercadopago_pay),
    path("public/settings/", views.public_site_settings),
]
